FASTFETCH_VERSION = 2.36.1
FASTFETCH_SITE = $(call github,fastfetch-cli,fastfetch,$(FASTFETCH_VERSION))
FASTFETCH_LICENSE = MIT
FASTFETCH_LICENSE_FILES = LICENSE

FASTFETCH_CONF_OPTS = \
	-DENABLE_X11=OFF \
	-DENABLE_WAYLAND=OFF \
	-DENABLE_DBUS=OFF \
	-DENABLE_DCONF=OFF \
	-DENABLE_VULKAN=OFF \
	-DENABLE_OPENGL=OFF \
	-DENABLE_OPENCL=OFF \
	-DENABLE_PCI=OFF \
	-DENABLE_RPM=OFF \
	-DENABLE_SYSTEM_YYJSON=OFF \
	-DBUILD_TESTS=OFF

$(eval $(cmake-package))
